# Generated by Django 5.1.4 on 2025-08-08 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousResellsBids',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='previous/')),
                ('year', models.IntegerField()),
                ('brand', models.CharField(max_length=70)),
                ('electronic_type', models.CharField(max_length=50)),
                ('generated_bid', models.FloatField()),
                ('generated_price', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
