# Generated by Django 5.1.4 on 2025-08-08 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resellApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previousresellsbids',
            old_name='generated_price',
            new_name='generated_resell',
        ),
    ]
