# Generated by Django 5.1.4 on 2025-08-11 00:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resellApp', '0002_rename_generated_price_previousresellsbids_generated_resell'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousresellsbids',
            name='description_optional',
            field=models.CharField(default=django.utils.timezone.now, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='previousresellsbids',
            name='model_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
