# Generated by Django 5.1.4 on 2025-08-11 01:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resellApp', '0003_previousresellsbids_description_optional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousresellsbids',
            name='condition',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='previousresellsbids',
            name='cpu',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='previousresellsbids',
            name='graphics',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='previousresellsbids',
            name='ram',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='previousresellsbids',
            name='screen_size',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='previousresellsbids',
            name='storage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
