# Generated by Django 5.1.4 on 2025-08-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resellApp', '0004_previousresellsbids_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousresellsbids',
            name='ram',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='previousresellsbids',
            name='screen_size',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='previousresellsbids',
            name='storage',
            field=models.IntegerField(default=0),
        ),
    ]
