# Generated by Django 5.1.4 on 2025-08-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resellApp', '0005_alter_previousresellsbids_ram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previousresellsbids',
            name='description_optional',
        ),
        migrations.RemoveField(
            model_name='previousresellsbids',
            name='graphics',
        ),
        migrations.RemoveField(
            model_name='previousresellsbids',
            name='image',
        ),
        migrations.AddField(
            model_name='previousresellsbids',
            name='conditionID',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='previousresellsbids',
            name='cpu_model',
            field=models.CharField(default='M1', max_length=25),
        ),
        migrations.AddField(
            model_name='previousresellsbids',
            name='cpu_tier',
            field=models.CharField(default='M1', max_length=25),
        ),
    ]
