# Generated by Django 5.1.4 on 2025-08-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resellApp', '0006_remove_previousresellsbids_description_optional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousresellsbids',
            name='generated_bid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
