# Generated by Django 5.1.4 on 2025-08-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resellApp', '0007_alter_previousresellsbids_generated_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousresellsbids',
            name='generated_resell',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
